### PR TITLE
Fix method overloading problem by displaying params too in chart

### LINKED ISSUE #29: Piechart bug
There is a bug when there is a class with method overloading. Beceause there are multiple methods with the same name the chartfactory will throw an exception

### PR DESCRIPTION
**Pull request by dandreescu**

### CODE REVIEW

File: src/main/java/gui/ChartFactory.java [hunk 1]
```diff
@@ -1,10 +1,12 @@
-package core;
+package gui;
```
Comment (bbrockbernd) [inline src/main/java/gui/ChartFactory.java:1]: Good choice to move it to gui

**Review by bbrockbernd — APPROVED** [review]

**Review by ioanasv — APPROVED** [review]
